export type ProductGroupRiskLevel = 'standard' | 'elevated' | 'restricted';

export type ProductGroupEligibility = 'enabled' | 'shadow' | 'disabled';

export type ProductGroupPackageUnit = 'ml' | 'g' | 'unit';

export type ProductGroupPriceNormalizer = 'per_liter' | 'per_kg' | 'per_unit';

export interface ProductGroupPackageSizeCompatibility {
  unit: ProductGroupPackageUnit;
  normalizeBy: ProductGroupPriceNormalizer;
  maxRatio: number;
}

export interface ProductGroupRegistryEntry {
  canonicalProductGroupKey: string;
  displayName: {
    tr: string;
    en: string;
  };
  department: string;
  category: string;
  coarseGroup: string;
  riskLevel: ProductGroupRiskLevel;
  alternativeEligibility: ProductGroupEligibility;
  healthierSwapEligibility: ProductGroupEligibility;
  matchAttributes: string[];
  softAttributes: string[];
  packageSizeCompatibility: ProductGroupPackageSizeCompatibility;
  minCandidatesForCard: number;
  betaCoverage: 'core' | 'expanded' | 'restricted';
  notes?: string;
}

export const PRODUCT_GROUP_REGISTRY: ProductGroupRegistryEntry[] = [
  {
    canonicalProductGroupKey: 'milk',
    displayName: { tr: 'Süt', en: 'Milk' },
    department: 'dairy',
    category: 'milk_and_cream',
    coarseGroup: 'dairy_drinkable',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['lactose_free', 'fat_level'],
    softAttributes: ['brand', 'organic', 'storage_type'],
    packageSizeCompatibility: { unit: 'ml', normalizeBy: 'per_liter', maxRatio: 4 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'lactose_free_milk',
    displayName: { tr: 'Laktozsuz süt', en: 'Lactose-free milk' },
    department: 'dairy',
    category: 'milk_and_cream',
    coarseGroup: 'dairy_drinkable',
    riskLevel: 'elevated',
    alternativeEligibility: 'shadow',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['lactose_free', 'fat_level'],
    softAttributes: ['brand', 'organic', 'storage_type'],
    packageSizeCompatibility: { unit: 'ml', normalizeBy: 'per_liter', maxRatio: 4 },
    minCandidatesForCard: 2,
    betaCoverage: 'expanded',
    notes: 'Keep separate from regular milk unless lactose-free matching is explicit.',
  },
  {
    canonicalProductGroupKey: 'kefir',
    displayName: { tr: 'Kefir', en: 'Kefir' },
    department: 'dairy',
    category: 'fermented_dairy_drinks',
    coarseGroup: 'dairy_drinkable',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: [],
    softAttributes: ['brand', 'flavor', 'organic'],
    packageSizeCompatibility: { unit: 'ml', normalizeBy: 'per_liter', maxRatio: 4 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'ayran',
    displayName: { tr: 'Ayran', en: 'Ayran' },
    department: 'dairy',
    category: 'fermented_dairy_drinks',
    coarseGroup: 'dairy_drinkable',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: [],
    softAttributes: ['brand', 'salt_level', 'organic'],
    packageSizeCompatibility: { unit: 'ml', normalizeBy: 'per_liter', maxRatio: 4 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'yogurt',
    displayName: { tr: 'Yoğurt', en: 'Yogurt' },
    department: 'dairy',
    category: 'yogurt',
    coarseGroup: 'dairy_spoonable',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['plain_or_fruit', 'fat_level'],
    softAttributes: ['brand', 'organic', 'strained'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'cheese',
    displayName: { tr: 'Peynir', en: 'Cheese' },
    department: 'dairy',
    category: 'cheese',
    coarseGroup: 'dairy_solid',
    riskLevel: 'standard',
    alternativeEligibility: 'shadow',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['cheese_type'],
    softAttributes: ['brand', 'fat_level', 'salt_level'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'expanded',
  },
  {
    canonicalProductGroupKey: 'egg',
    displayName: { tr: 'Yumurta', en: 'Eggs' },
    department: 'dairy',
    category: 'eggs',
    coarseGroup: 'eggs',
    riskLevel: 'standard',
    alternativeEligibility: 'shadow',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['count'],
    softAttributes: ['brand', 'size_class', 'free_range', 'organic'],
    packageSizeCompatibility: { unit: 'unit', normalizeBy: 'per_unit', maxRatio: 3 },
    minCandidatesForCard: 2,
    betaCoverage: 'expanded',
  },
  {
    canonicalProductGroupKey: 'chips',
    displayName: { tr: 'Cips', en: 'Chips' },
    department: 'snacks',
    category: 'salty_snacks',
    coarseGroup: 'snacks_salty',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['base_ingredient'],
    softAttributes: ['brand', 'flavor', 'baked_or_fried'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 4 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'cracker',
    displayName: { tr: 'Kraker', en: 'Cracker' },
    department: 'snacks',
    category: 'salty_snacks',
    coarseGroup: 'snacks_salty',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: [],
    softAttributes: ['brand', 'flavor', 'whole_grain'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 4 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'biscuit',
    displayName: { tr: 'Bisküvi', en: 'Biscuit' },
    department: 'snacks',
    category: 'sweet_snacks',
    coarseGroup: 'snacks_sweet',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: [],
    softAttributes: ['brand', 'flavor', 'cream_filled'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 4 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'wafer',
    displayName: { tr: 'Gofret', en: 'Wafer' },
    department: 'snacks',
    category: 'sweet_snacks',
    coarseGroup: 'snacks_sweet',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: [],
    softAttributes: ['brand', 'flavor'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 4 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'chocolate',
    displayName: { tr: 'Çikolata', en: 'Chocolate' },
    department: 'snacks',
    category: 'chocolate',
    coarseGroup: 'snacks_sweet',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['chocolate_type'],
    softAttributes: ['brand', 'cocoa_percent', 'filling'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 4 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'oat_bar',
    displayName: { tr: 'Yulaf bar', en: 'Oat bar' },
    department: 'snacks',
    category: 'bars',
    coarseGroup: 'snacks_bars',
    riskLevel: 'standard',
    alternativeEligibility: 'shadow',
    healthierSwapEligibility: 'disabled',
    matchAttributes: [],
    softAttributes: ['brand', 'flavor', 'protein_claim'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 4 },
    minCandidatesForCard: 2,
    betaCoverage: 'expanded',
  },
  {
    canonicalProductGroupKey: 'pasta',
    displayName: { tr: 'Makarna', en: 'Pasta' },
    department: 'pantry',
    category: 'grains_and_pasta',
    coarseGroup: 'dry_grains',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['gluten_free'],
    softAttributes: ['brand', 'shape', 'whole_wheat'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'rice',
    displayName: { tr: 'Pirinç', en: 'Rice' },
    department: 'pantry',
    category: 'grains_and_pulses',
    coarseGroup: 'dry_grains',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['rice_type'],
    softAttributes: ['brand', 'origin'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'bulgur',
    displayName: { tr: 'Bulgur', en: 'Bulgur' },
    department: 'pantry',
    category: 'grains_and_pulses',
    coarseGroup: 'dry_grains',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['grain_size'],
    softAttributes: ['brand', 'origin'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'lentils',
    displayName: { tr: 'Mercimek', en: 'Lentils' },
    department: 'pantry',
    category: 'grains_and_pulses',
    coarseGroup: 'pulses',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['lentil_type'],
    softAttributes: ['brand', 'origin'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'flour',
    displayName: { tr: 'Un', en: 'Flour' },
    department: 'pantry',
    category: 'baking',
    coarseGroup: 'baking_staples',
    riskLevel: 'standard',
    alternativeEligibility: 'shadow',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['flour_type'],
    softAttributes: ['brand', 'protein_level'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'expanded',
  },
  {
    canonicalProductGroupKey: 'sugar',
    displayName: { tr: 'Şeker', en: 'Sugar' },
    department: 'pantry',
    category: 'baking',
    coarseGroup: 'baking_staples',
    riskLevel: 'standard',
    alternativeEligibility: 'shadow',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['sugar_type'],
    softAttributes: ['brand'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'expanded',
  },
  {
    canonicalProductGroupKey: 'olive_oil',
    displayName: { tr: 'Zeytinyağı', en: 'Olive oil' },
    department: 'pantry',
    category: 'oils',
    coarseGroup: 'oils',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['oil_type'],
    softAttributes: ['brand', 'extra_virgin', 'origin'],
    packageSizeCompatibility: { unit: 'ml', normalizeBy: 'per_liter', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'sunflower_oil',
    displayName: { tr: 'Ayçiçek yağı', en: 'Sunflower oil' },
    department: 'pantry',
    category: 'oils',
    coarseGroup: 'oils',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['oil_type'],
    softAttributes: ['brand'],
    packageSizeCompatibility: { unit: 'ml', normalizeBy: 'per_liter', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'tomato_paste',
    displayName: { tr: 'Salça', en: 'Tomato paste' },
    department: 'pantry',
    category: 'sauces_and_pastes',
    coarseGroup: 'cooking_pastes',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['paste_type'],
    softAttributes: ['brand', 'salt_level'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'canned_tuna',
    displayName: { tr: 'Konserve ton balığı', en: 'Canned tuna' },
    department: 'pantry',
    category: 'canned_food',
    coarseGroup: 'canned_fish',
    riskLevel: 'standard',
    alternativeEligibility: 'shadow',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['preservation_medium'],
    softAttributes: ['brand', 'drained_weight'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 4 },
    minCandidatesForCard: 2,
    betaCoverage: 'expanded',
  },
  {
    canonicalProductGroupKey: 'water',
    displayName: { tr: 'Su', en: 'Water' },
    department: 'beverages',
    category: 'water',
    coarseGroup: 'water_beverage',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: [],
    softAttributes: ['brand', 'spring_or_mineral'],
    packageSizeCompatibility: { unit: 'ml', normalizeBy: 'per_liter', maxRatio: 6 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'sparkling_water',
    displayName: { tr: 'Maden suyu', en: 'Sparkling water' },
    department: 'beverages',
    category: 'water',
    coarseGroup: 'water_beverage',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['plain_or_flavored'],
    softAttributes: ['brand', 'mineral_level'],
    packageSizeCompatibility: { unit: 'ml', normalizeBy: 'per_liter', maxRatio: 6 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'cola',
    displayName: { tr: 'Kola', en: 'Cola' },
    department: 'beverages',
    category: 'soft_drinks',
    coarseGroup: 'soft_drink',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['sugar_free'],
    softAttributes: ['brand', 'flavor'],
    packageSizeCompatibility: { unit: 'ml', normalizeBy: 'per_liter', maxRatio: 6 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'fruit_juice',
    displayName: { tr: 'Meyve suyu', en: 'Fruit juice' },
    department: 'beverages',
    category: 'juices',
    coarseGroup: 'juice_drink',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['juice_percent'],
    softAttributes: ['brand', 'fruit_type', 'sugar_added'],
    packageSizeCompatibility: { unit: 'ml', normalizeBy: 'per_liter', maxRatio: 6 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'tea',
    displayName: { tr: 'Çay', en: 'Tea' },
    department: 'beverages',
    category: 'hot_drinks',
    coarseGroup: 'hot_drinks',
    riskLevel: 'standard',
    alternativeEligibility: 'shadow',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['tea_type'],
    softAttributes: ['brand', 'origin'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'expanded',
  },
  {
    canonicalProductGroupKey: 'coffee',
    displayName: { tr: 'Kahve', en: 'Coffee' },
    department: 'beverages',
    category: 'hot_drinks',
    coarseGroup: 'hot_drinks',
    riskLevel: 'standard',
    alternativeEligibility: 'shadow',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['coffee_type'],
    softAttributes: ['brand', 'roast_level'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'expanded',
  },
  {
    canonicalProductGroupKey: 'breakfast_cereal',
    displayName: { tr: 'Kahvaltılık gevrek', en: 'Breakfast cereal' },
    department: 'breakfast',
    category: 'cereal',
    coarseGroup: 'breakfast',
    riskLevel: 'standard',
    alternativeEligibility: 'enabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: [],
    softAttributes: ['brand', 'flavor', 'whole_grain'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'core',
  },
  {
    canonicalProductGroupKey: 'jam',
    displayName: { tr: 'Reçel', en: 'Jam' },
    department: 'breakfast',
    category: 'spreads',
    coarseGroup: 'breakfast_spreads',
    riskLevel: 'standard',
    alternativeEligibility: 'shadow',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['fruit_type'],
    softAttributes: ['brand', 'sugar_free'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'expanded',
  },
  {
    canonicalProductGroupKey: 'honey',
    displayName: { tr: 'Bal', en: 'Honey' },
    department: 'breakfast',
    category: 'spreads',
    coarseGroup: 'breakfast_spreads',
    riskLevel: 'standard',
    alternativeEligibility: 'shadow',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['honey_type'],
    softAttributes: ['brand', 'origin'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 5 },
    minCandidatesForCard: 2,
    betaCoverage: 'expanded',
  },
  {
    canonicalProductGroupKey: 'baby_formula',
    displayName: { tr: 'Bebek devam sütü', en: 'Baby formula' },
    department: 'baby',
    category: 'baby_formula',
    coarseGroup: 'baby_food',
    riskLevel: 'restricted',
    alternativeEligibility: 'disabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['baby_age_range', 'medical_claim'],
    softAttributes: ['brand', 'package_type'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 4 },
    minCandidatesForCard: 3,
    betaCoverage: 'restricted',
    notes: 'Restricted in beta unless human-curated allowlist is introduced.',
  },
  {
    canonicalProductGroupKey: 'baby_cereal',
    displayName: { tr: 'Bebek tahıl kaşığı maması', en: 'Baby cereal' },
    department: 'baby',
    category: 'baby_food',
    coarseGroup: 'baby_food',
    riskLevel: 'restricted',
    alternativeEligibility: 'disabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['baby_age_range'],
    softAttributes: ['brand', 'grain_type'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 4 },
    minCandidatesForCard: 3,
    betaCoverage: 'restricted',
  },
  {
    canonicalProductGroupKey: 'baby_food',
    displayName: { tr: 'Bebek maması', en: 'Baby food' },
    department: 'baby',
    category: 'baby_food',
    coarseGroup: 'baby_food',
    riskLevel: 'restricted',
    alternativeEligibility: 'disabled',
    healthierSwapEligibility: 'disabled',
    matchAttributes: ['baby_age_range', 'meal_type'],
    softAttributes: ['brand', 'flavor'],
    packageSizeCompatibility: { unit: 'g', normalizeBy: 'per_kg', maxRatio: 4 },
    minCandidatesForCard: 3,
    betaCoverage: 'restricted',
  },
];

export function findProductGroupRegistryEntry(
  canonicalProductGroupKey: string,
): ProductGroupRegistryEntry | undefined {
  return PRODUCT_GROUP_REGISTRY.find(
    (entry) => entry.canonicalProductGroupKey === canonicalProductGroupKey,
  );
}
